
import { JobListing } from '../../types';

export const jobListings: JobListing[] = [
  {
    id: "job-1",
    title: "Senior Frontend Developer",
    company: "TechGrowth Inc.",
    description: "We are looking for a Senior Frontend Developer to join our team. You will be responsible for building user interfaces for our web applications using React, TypeScript, and related technologies. The ideal candidate will have strong experience with modern frontend frameworks, state management, and responsive design.",
    country: "United States",
    url: "https://example.com/job/senior-frontend",
    date: "2023-05-15",
    sponsorship: true,
    minYearsExperience: 5,
    minEducation: "Bachelor's",
    positionLevel: "Senior",
    keywords: ["React", "TypeScript", "Redux", "CSS", "Frontend"],
    recruiterId: "user-2",
    recruiterName: "Jordan Smith",
    createdAt: "2023-05-10T09:00:00Z",
    updatedAt: "2023-05-10T09:00:00Z"
  },
  {
    id: "job-2",
    title: "Full Stack Engineer",
    company: "Innovate Solutions",
    description: "Innovate Solutions is seeking a Full Stack Engineer who is passionate about building scalable web applications. You'll work across the entire stack using technologies like Node.js, React, MongoDB, and AWS. The role involves designing and implementing new features, optimizing application performance, and collaborating with cross-functional teams.",
    country: "Germany",
    url: "https://example.com/job/fullstack-engineer",
    date: "2023-05-20",
    sponsorship: true,
    minYearsExperience: 3,
    minEducation: "Bachelor's",
    positionLevel: "Mid-level",
    keywords: ["Node.js", "React", "MongoDB", "AWS", "Full Stack"],
    recruiterId: "user-3",
    recruiterName: "Alex Johnson",
    createdAt: "2023-05-12T14:30:00Z",
    updatedAt: "2023-05-12T14:30:00Z"
  },
  {
    id: "job-3",
    title: "Machine Learning Engineer",
    company: "DataAI Corp",
    description: "DataAI Corp is looking for a talented Machine Learning Engineer to join our AI research team. You will design and implement machine learning models, work with large datasets, and collaborate with data scientists and engineers to integrate ML systems into our products. Experience with Python, TensorFlow/PyTorch, and cloud ML services is required.",
    country: "Canada",
    url: "https://example.com/job/ml-engineer",
    date: "2023-06-01",
    sponsorship: false,
    minYearsExperience: 4,
    minEducation: "Master's",
    positionLevel: "Senior",
    keywords: ["Python", "TensorFlow", "PyTorch", "Machine Learning", "AI"],
    recruiterId: "user-2",
    recruiterName: "Jordan Smith",
    createdAt: "2023-05-15T11:15:00Z",
    updatedAt: "2023-05-15T11:15:00Z"
  },
  {
    id: "job-4",
    title: "DevOps Engineer",
    company: "Cloud Systems Ltd",
    description: "Cloud Systems is hiring a DevOps Engineer to help build and maintain our cloud infrastructure. You'll be responsible for CI/CD pipelines, infrastructure as code, monitoring solutions, and security best practices. The ideal candidate has experience with AWS/Azure, Kubernetes, Terraform, and automation tools.",
    country: "United Kingdom",
    url: "https://example.com/job/devops-engineer",
    date: "2023-05-25",
    sponsorship: true,
    minYearsExperience: 3,
    minEducation: "Bachelor's",
    positionLevel: "Mid-level",
    keywords: ["AWS", "Kubernetes", "Terraform", "Docker", "DevOps"],
    recruiterId: "user-3",
    recruiterName: "Alex Johnson",
    createdAt: "2023-05-18T10:45:00Z",
    updatedAt: "2023-05-18T10:45:00Z"
  },
  {
    id: "job-5",
    title: "Backend Developer",
    company: "Secure Payments Inc",
    description: "Secure Payments is looking for a Backend Developer with strong experience in building RESTful APIs and microservices. You'll be working with Java, Spring Boot, and PostgreSQL to develop our payment processing platform. Knowledge of security best practices and payment systems is a plus.",
    country: "Singapore",
    url: "https://example.com/job/backend-developer",
    date: "2023-06-05",
    sponsorship: true,
    minYearsExperience: 4,
    minEducation: "Bachelor's",
    positionLevel: "Senior",
    keywords: ["Java", "Spring Boot", "PostgreSQL", "Microservices", "API"],
    recruiterId: "user-2",
    recruiterName: "Jordan Smith",
    createdAt: "2023-05-20T13:00:00Z",
    updatedAt: "2023-05-20T13:00:00Z"
  }
];
